plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
    - tmp/**/*
    - coverage/**/*
    - log/**/*
    - public/**/*
    - .github/**/*
    - .git/**/*
    - .ruby-lsp/**/*
  TargetRubyVersion: 3.4
  DisplayCopNames: true
  NewCops: enable

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/ClassLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

# Spec-related overrides below

Style/Documentation:
  Exclude:
    - "spec/**/*"

Metrics/ModuleLength:
  Exclude:
    - spec/**/*'

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*
  Max: 15

Metrics/CyclomaticComplexity:
  Exclude:
    - spec/**/*
  Max: 10

Metrics/PerceivedComplexity:
  Exclude:
    - spec/**/*
  Max: 10

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false
