require:
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
  TargetRubyVersion: 3.4
  DisplayCopNames: true
  NewCops: enable

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# Spec-related overrides below

Style/Documentation:
  Exclude:
    - "spec/**/*"

Metrics/ModuleLength:
  Exclude:
    - spec/**/*'

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false
