default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: groceries_service_development
test:
  <<: *default
  database: groceries_service_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
