default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: groceries_service_development
  host: <%= ENV.fetch("RAILS_DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("RAILS_DB_USER") { '' } %>
  password: <%= ENV.fetch("RAILS_DB_PASS") { '' } %>
test:
  <<: *default
  database: groceries_service_test
  host: <%= ENV.fetch("RAILS_DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("RAILS_DB_USER") { '' } %>
  password: <%= ENV.fetch("RAILS_DB_PASS") { '' } %>
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
