on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scans staging
    steps:
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: "https://cjb-groceries-staging.herokuapp.com"
