on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  zap_scan:
    name: Scans staging
    steps:
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: "https://staging.groceries-app.com"
